Repository WildCodeSchool/2023-03-JS-TLSE-P2-quizilla, pull requests merged in 2023-05, with the labels that each got.

#36 S4 fix fetch
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Navbar.css
  frontend/src/components/Question.css
  frontend/src/components/Question.jsx
  frontend/src/components/Timer.jsx
  frontend/src/main.jsx
  frontend/src/pages/AboutUs.css
  frontend/src/pages/GameBoard.jsx
  frontend/src/pages/Quiz.jsx
  frontend/src/pages/Rules.css
  package-lock.json
  package.json
Labels: Reviewed

#39 S3 us20winner
  frontend/src/components/Navbar.css
  frontend/src/components/Navbar.jsx
  frontend/src/components/Utils.js
  frontend/src/index.css
  frontend/src/pages/Home.jsx
  frontend/src/pages/Loser.jsx
  frontend/src/pages/Winner.css
  frontend/src/pages/Winner.jsx
  package-lock.json
  package.json
Labels: Reviewed, Corrections done

#40 S4 us07/08 algo
  frontend/package-lock.json
  frontend/package.json
  frontend/public/assets/LifeBoard.svg
  frontend/src/App.jsx
  frontend/src/components/Question.jsx
  frontend/src/components/SpinWheel.jsx
  frontend/src/components/Timer.jsx
  frontend/src/pages/GameBoard.css
  frontend/src/pages/GameBoard.jsx
  frontend/src/pages/Quiz.jsx
Labels: Reviewed

#41 S4 renove css
  frontend/src/components/Settings.css
  frontend/src/pages/Home.css
Labels: Reviewed

#42 Principal features ok
  .vscode/settings.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/assets/LifeBoard.svg
  frontend/public/assets/alain.jpg
  frontend/public/assets/ante.jpg
  frontend/public/assets/cyrille.jpg
  frontend/public/assets/junior.jpg
  frontend/src/App.jsx
  frontend/src/components/Navbar.css
  frontend/src/components/Navbar.jsx
  frontend/src/components/Question.css
  frontend/src/components/Question.jsx
  frontend/src/components/Settings.css
  frontend/src/components/Settings.jsx
  frontend/src/components/SpinWheel.css
  frontend/src/components/SpinWheel.jsx
  frontend/src/components/Square.jsx
  frontend/src/components/Timer.jsx
  frontend/src/components/Utils.js
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/pages/AboutUs.css
  frontend/src/pages/AboutUs.jsx
  frontend/src/pages/GameBoard.css
  frontend/src/pages/GameBoard.jsx
  frontend/src/pages/Home.css
  frontend/src/pages/Home.jsx
  frontend/src/pages/Loser.jsx
  frontend/src/pages/Quiz.css
  frontend/src/pages/Quiz.jsx
  frontend/src/pages/Rules.css
  frontend/src/pages/Rules.jsx
  frontend/src/pages/Winner.css
  frontend/src/pages/Winner.jsx
  l'extrémité avant/src/pages/Home.css
  package-lock.json
  package.json
Labels: Reviewed

#43 S4US08MapSquare*
  frontend/src/components/Utils.js
  frontend/src/pages/GameBoard.jsx
Labels: Reviewed

#45 S4 us06 navbar
  frontend/src/App.jsx
  frontend/src/components/Navbar.css
  frontend/src/components/Navbar.jsx
Labels: Reviewed

#46 S4 us04winner
  frontend/src/components/Utils.js
  frontend/src/pages/Loser.jsx
  frontend/src/pages/Winner.css
  frontend/src/pages/Winner.jsx
Labels: Corrections done

#47 S4valid gameboard
  frontend/src/App.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/Square.jsx
  frontend/src/pages/GameBoard.jsx
Labels: Reviewed

#48 S4 us7 navbar
  frontend/src/components/Navbar.css
  frontend/src/components/Navbar.jsx
Labels: Reviewed

#51 S4 us04winner
  frontend/src/pages/Winner.css
Labels: Reviewed

#52 S4_US04 fix newGame:hover
  frontend/src/pages/Loser.jsx
  frontend/src/pages/Winner.css
  frontend/src/pages/Winner.jsx
Labels: Reviewed, Corrections done

#54 S4 Algo combined difficulty ok
  frontend/src/App.jsx
  frontend/src/pages/Quiz.jsx
Labels: Reviewed

#56 S4 Error width done
  frontend/src/pages/GameBoard.jsx
Labels: Reviewed

#58 S4 responsive loader
  frontend/src/components/Loader.css
  frontend/src/components/Settings.css
Labels: Reviewed

#59 S4 Fix score
  frontend/src/components/Utils.js
  frontend/src/pages/Quiz.jsx
Labels: Reviewed

#60 S4 css fix
  frontend/public/assets/ColoredGeneralKnowledge_Icon.svg
  frontend/public/assets/ColoredGeography_Icon.svg
  frontend/public/assets/ColoredHistory_Icon.svg
  frontend/public/assets/ColoredMusic_Icon.svg
  frontend/public/assets/ColoredScience&Nature_Icon.svg
  frontend/public/assets/ColoredVideoGames_Icon.svg
  frontend/public/assets/redLife_Icon.svg
  frontend/src/components/Navbar.css
  frontend/src/components/Square.jsx
  frontend/src/index.css
  frontend/src/pages/AboutUs.css
  frontend/src/pages/AboutUs.jsx
  frontend/src/pages/GameBoard.css
  frontend/src/pages/GameBoard.jsx
  frontend/src/pages/Home.css
  frontend/src/pages/Loser.jsx
  frontend/src/pages/Rules.css
  frontend/src/pages/Rules.jsx
  frontend/src/pages/Winner.css
  frontend/src/pages/Winner.jsx
Labels: Reviewed

#62 S4 Hot Fix Css
  frontend/src/components/Navbar.jsx
  frontend/src/components/Square.jsx
  frontend/src/index.css
  frontend/src/pages/AboutUs.css
Labels: Reviewed
